name: CI/CD Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**'

env:
  LOCAL_DOCKER_REGISTRY: ${{ vars.LOCAL_DOCKER_REGISTRY }}
  DOCKERFILE_PATH: ${{ vars.DOCKERFILE_PATH }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
  CONTAINER_EXPOSE_PORT: ${{ vars.CONTAINER_EXPOSE_PORT }}
  HOST_EXPOSE_PORT: ${{ vars.HOST_EXPOSE_PORT }}

jobs:
  build-push-deploy:
    runs-on: PROD-GH-RUNNER-01
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[A-Z]' 'a-z')
          VERSION_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION_TAG=$(echo $VERSION_TAG | sed -e 's/^v//')
          FULL_DOCKER_IMAGE_NAME=$LOCAL_DOCKER_REGISTRY/$IMAGE_NAME_LOWER:$VERSION_TAG
          echo "FULL_DOCKER_IMAGE_NAME=$FULL_DOCKER_IMAGE_NAME" >> $GITHUB_ENV
          sudo docker build . --file $DOCKERFILE_PATH --tag $FULL_DOCKER_IMAGE_NAME
      - name: Push Docker image to Local Registry
        run: |
          sudo docker push $FULL_DOCKER_IMAGE_NAME
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ vars.DEPLOY_SERVER_IP }}
          username: actionsrunner
          key: ${{ secrets.PROD_RUNNER_SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ env.FULL_DOCKER_IMAGE_NAME }}
            sudo docker stop ${{ vars.CONTAINER_NAME }} || true
            sudo docker rm -f ${{ vars.CONTAINER_NAME }} || true
            sudo docker run -d --restart=unless-stopped --name ${{ vars.CONTAINER_NAME }} \
                            --add-host mysql-01.allpayway.org:192.168.100.20 \
                            --add-host leaderpay.ge:192.168.100.30 \
                            --add-host wallet.leaderpay.ge:192.168.100.30 \
                            --add-host api.allpayway.ge:192.168.100.30 \
                            --add-host manager.allpayway.ge:192.168.100.30 \
                            --add-host cashdesk.allpayway.ge:192.168.100.30 \
                            --add-host leaderbet.allpayway.ge:192.168.100.30 \
                            --add-host uploads.allpayway.ge:192.168.100.30 \
                            --add-host allpayway.ge:192.168.100.30 \
                            --add-host pay.allpayway.ge:192.168.100.30 \
                            --add-host allpayment.ge:192.168.100.30 \
                            --add-host api.apw.ge:192.168.100.30 \
                            --add-host admin.apw.ge:192.168.100.30 \
                            --add-host apw.ge:192.168.100.30 \
                            --add-host main.merchant.apw.ge:192.168.100.30 \
                            --add-host merchant.apw.ge:192.168.100.30 \
                            --add-host studypay.ge:192.168.100.30 \
                            --add-host admin.studypay.ge:192.168.100.30 \
                            --add-host back.studypay.ge:192.168.100.30 \
                            --add-host devspace.ge:192.168.100.30 \
                            --add-host back.devspace.ge:192.168.100.30 \
                            --add-host screening.payway.ge:192.168.100.30 \
                            -p ${{ vars.HOST_EXPOSE_PORT }}:${{ vars.CONTAINER_EXPOSE_PORT }} ${{ env.FULL_DOCKER_IMAGE_NAME }}
